### PR TITLE
Us admin comic edit request

### PR DESCRIPTION
**Pull request by vincentDubresson**

### CODE REVIEW

**Review by aldaitzwild — CHANGES_REQUESTED** [review]
conflict with dev

**Comment by vincentDubresson** [comment]
Conflicts resolved.

**Review by aldaitzwild — CHANGES_REQUESTED** [review]
New conflicts with dev

**Comment by vincentDubresson** [comment]
Conflicts Resolved

**Review by aldaitzwild — APPROVED** [review]

**Pull request merged**
